### ISSUE TITLE
Initial suggestions

### ISSUE THREAD

**Issue by noamross** [n8layman/chad#1]
1) Using `rlang::last_trace()` and related calls you could provide the LLM with not just the error, but the function call and potentially the whole call stack, which could give a better diagnosis.  If you go nuts you could do other things like capture the environment in the future. 

2) Allow the user to set the model, with the default being set by a global env var or option.

3) Consider making the prompt itself something that can be set with an option, to enable experimentation.  Personally I find the multiple steps to debug that it suggests a little verbose.

**Comment by n8layman** [comment]
Yeah, I was just working on finishing the trace bit before I get back to working on other more important stuff. The trace part fell off the wagon somewhere along the line. The best way to give OpenAI the trace might be as a JSON object which would require converting it to a nested list first. Any suggestions?

**Comment by n8layman** [comment]
Maybe `rlang::last_error()$trace[[1]]` would be enough.

**Comment by n8layman** [comment]
Okay first pass at adding the trace pushed.

**Comment by n8layman** [comment]
Okay, the other two suggestions have been implemented as well. Thanks for the feedback!

**Comment by n8layman** [comment]
Closing as everything but capturing the environment has now been added.
